rm(list=ls())
install.packages("quantmod")
install.packages("ggplot2")
install.packages("forecast")
install.packages("dplyr")
install.packages("xts", repos="http://cloud.r-project.org")
library(forecast)
library(dplyr) 
library(quantmod)
library(ggplot2)
library(xts)
library("TTR")

g <- getSymbols(c("GME"), src = "yahoo", from = "2015-01-01", to = "2021-12-31",auto.assign=FALSE)
gme <- ts(g$GME.Adjusted, start=c(2015, 1), end=c(2021, 12),frequency=365)
plot(gme)

train <- head(Cl(g), length(Cl(g))-100)
test <- tail(Cl(g), 100)

gme_ma <- ma(train,5)
autoplot(gme_ma)+autolayer(ts(test,start=length(train)),series="Test Data")
summary(gme_ma)

gme_na <- naive(train,h=100)
autoplot(gme_na)+autolayer(ts(test,start=length(train)),series="Test Data")
summary(gme_na)

gme_ses <- ses(train,h=100,alpha=0.15)
autoplot(gme_ses)+autolayer(ts(test,start=length(train)),series="Test Data")
summary(gme_ses)

gme_h <- holt(train,h=100)
autoplot(gme_h)+autolayer(ts(test,start=length(train)),series="Test Data")
summary(gme_h)

gme_hw <- HoltWinters(gme,beta=TRUE,gamma=FALSE)
plot(gme_hw)
summary(gme_hw)

g_pre <- getSymbols(c("GME"), src = "yahoo", from = "2015-01-01", to = "2019-12-31",auto.assign=FALSE)
g_post <- getSymbols(c("GME"), src = "yahoo", from = "2020-01-01", to = "2021-12-31",auto.assign=FALSE)
gme_pre <- ts(g_pre$GME.Adjusted, start=c(2015, 1), end=c(2019, 12),frequency=365)
gme_post <- ts(g$GME.Adjusted, start=c(2020, 1), end=c(2021, 12),frequency=365)

train_pre <- head(Cl(g_pre), length(Cl(g_pre))-100)
test_pre <- tail(Cl(g_pre), 100)

train_post <- head(Cl(g_post), length(Cl(g_post))-100)
test_post <- tail(Cl(g_post), 100)

gme_ma_pre <- ma(train_pre,5)
autoplot(gme_ma_pre)+autolayer(ts(test_pre,start=length(train_pre)),series="Test Data")
summary(gme_ma_pre)
gme_ma_post <- ma(train_post,5)
autoplot(gme_ma_post)+autolayer(ts(test_post,start=length(train_post)),series="Test Data")
summary(gme_ma_post)

gme_na_pre <- naive(train_pre,h=100)
autoplot(gme_na_pre)+autolayer(ts(test_pre,start=length(train_pre)),series="Test Data")
summary(gme_na_pre)
gme_na_post <- naive(train_post,h=100)
autoplot(gme_na_post)+autolayer(ts(test_post,start=length(train_post)),series="Test Data")
summary(gme_na_post)

gme_ses_pre <- ses(train_pre,h=100,alpha=0.15)
autoplot(gme_ses_pre)+autolayer(ts(test_pre,start=length(train_pre)),series="Test Data")
summary(gme_ses_pre)
gme_ses_post <- ses(train_post,h=100,alpha=0.15)
autoplot(gme_ses_post)+autolayer(ts(test_post,start=length(train_post)),series="Test Data")
summary(gme_ses_post)

gme_h_pre <- holt(train_pre,h=100)
autoplot(gme_h_pre)+autolayer(ts(test_pre,start=length(train_pre)),series="Test Data")
summary(gme_h_pre)
gme_h_post <- holt(train_post,h=100)
autoplot(gme_h_post)+autolayer(ts(test_post,start=length(train_post)),series="Test Data")
summary(gme_h_post)

gme_hw_pre <- HoltWinters(gme_pre,beta=TRUE,gamma=FALSE)
plot(gme_hw_pre)
summary(gme_hw_pre)
gme_hw_post <- HoltWinters(gme_post,beta=TRUE,gamma=FALSE)
plot(gme_hw_post)
summary(gme_hw_post)
